
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'AND DIVIDE EQUAL INF LPAREN MINUS NAME NUMBER OR PLUS RPAREN SEMI SUP TIMESbloc : bloc statement SEMI \n| statement SEMIstatement : NAME EQUAL expressionstatement : expressionexpression : expression INF expressionexpression : expression SUP expressionexpression : expression AND expressionexpression : expression OR expressionexpression : expression PLUS expressionexpression : expression TIMES expressionexpression : expression MINUS expression\n| expression DIVIDE expressionexpression : LPAREN expression RPARENexpression : NUMBERexpression : NAME'
    
_lr_action_items = {'NAME':([0,1,5,8,9,10,11,12,13,14,15,16,17,20,],[3,3,19,-2,19,19,19,19,19,19,19,19,19,-1,]),'LPAREN':([0,1,5,8,9,10,11,12,13,14,15,16,17,20,],[5,5,5,-2,5,5,5,5,5,5,5,5,5,-1,]),'NUMBER':([0,1,5,8,9,10,11,12,13,14,15,16,17,20,],[6,6,6,-2,6,6,6,6,6,6,6,6,6,-1,]),'$end':([1,8,20,],[0,-2,-1,]),'SEMI':([2,3,4,6,7,19,21,22,23,24,25,26,27,28,29,30,],[8,-15,-4,-14,20,-15,-3,-5,-6,-7,-8,-9,-10,-11,-12,-13,]),'EQUAL':([3,],[9,]),'INF':([3,4,6,18,19,21,22,23,24,25,26,27,28,29,30,],[-15,10,-14,10,-15,10,10,10,10,10,10,10,10,10,-13,]),'SUP':([3,4,6,18,19,21,22,23,24,25,26,27,28,29,30,],[-15,11,-14,11,-15,11,11,11,11,11,11,11,11,11,-13,]),'AND':([3,4,6,18,19,21,22,23,24,25,26,27,28,29,30,],[-15,12,-14,12,-15,12,12,12,12,12,12,12,12,12,-13,]),'OR':([3,4,6,18,19,21,22,23,24,25,26,27,28,29,30,],[-15,13,-14,13,-15,13,13,13,13,13,13,13,13,13,-13,]),'PLUS':([3,4,6,18,19,21,22,23,24,25,26,27,28,29,30,],[-15,14,-14,14,-15,14,14,14,14,14,14,14,14,14,-13,]),'TIMES':([3,4,6,18,19,21,22,23,24,25,26,27,28,29,30,],[-15,15,-14,15,-15,15,15,15,15,15,15,15,15,15,-13,]),'MINUS':([3,4,6,18,19,21,22,23,24,25,26,27,28,29,30,],[-15,16,-14,16,-15,16,16,16,16,16,16,16,16,16,-13,]),'DIVIDE':([3,4,6,18,19,21,22,23,24,25,26,27,28,29,30,],[-15,17,-14,17,-15,17,17,17,17,17,17,17,17,17,-13,]),'RPAREN':([6,18,19,22,23,24,25,26,27,28,29,30,],[-14,30,-15,-5,-6,-7,-8,-9,-10,-11,-12,-13,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'bloc':([0,],[1,]),'statement':([0,1,],[2,7,]),'expression':([0,1,5,9,10,11,12,13,14,15,16,17,],[4,4,18,21,22,23,24,25,26,27,28,29,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> bloc","S'",1,None,None,None),
  ('bloc -> bloc statement SEMI','bloc',3,'p_bloc','calcBase.py',49),
  ('bloc -> statement SEMI','bloc',2,'p_bloc','calcBase.py',50),
  ('statement -> NAME EQUAL expression','statement',3,'p_statement_assign','calcBase.py',53),
  ('statement -> expression','statement',1,'p_statement_expr','calcBase.py',56),
  ('expression -> expression INF expression','expression',3,'p_expression_binop_inf','calcBase.py',61),
  ('expression -> expression SUP expression','expression',3,'p_expression_binop_sup','calcBase.py',65),
  ('expression -> expression AND expression','expression',3,'p_expression_binop_and','calcBase.py',69),
  ('expression -> expression OR expression','expression',3,'p_expression_binop_or','calcBase.py',73),
  ('expression -> expression PLUS expression','expression',3,'p_expression_binop_plus','calcBase.py',77),
  ('expression -> expression TIMES expression','expression',3,'p_expression_binop_times','calcBase.py',81),
  ('expression -> expression MINUS expression','expression',3,'p_expression_binop_divide_and_minus','calcBase.py',85),
  ('expression -> expression DIVIDE expression','expression',3,'p_expression_binop_divide_and_minus','calcBase.py',86),
  ('expression -> LPAREN expression RPAREN','expression',3,'p_expression_group','calcBase.py',91),
  ('expression -> NUMBER','expression',1,'p_expression_number','calcBase.py',95),
  ('expression -> NAME','expression',1,'p_expression_name','calcBase.py',99),
]
